/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Bipin Pandey",
  "tagline": "Information Architect | AI in Documentation | Strategic Content Manager",
  "favicon": "img/favicon.ico",
  "url": "https://bipin-24.github.io",
  "baseUrl": "/",
  "organizationName": "Bipin-24",
  "projectName": "portfolio",
  "trailingSlash": false,
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.js",
          "routeBasePath": "portfolio",
          "editUrl": "https://github.com/Bipin-24/portfolio-site/edit/main/",
          "showLastUpdateTime": true
        },
        "blog": {
          "showReadingTime": true,
          "blogTitle": "Insights & AI in Information Architecture",
          "blogDescription": "Exploring the intersection of Information Architecture, AI, and Content Experience.",
          "postsPerPage": 5,
          "feedOptions": {
            "type": "all",
            "title": "Bipin Pandey Blog Feed"
          }
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        },
        "sitemap": {
          "lastmod": "date",
          "changefreq": "weekly",
          "priority": 0.7,
          "filename": "sitemap.xml"
        }
      }
    ]
  ],
  "plugins": [
    [
      "@docusaurus/plugin-content-pages",
      {
        "id": "about-page",
        "path": "about",
        "routeBasePath": "about"
      }
    ]
  ],
  "themeConfig": {
    "image": "img/social-preview.png",
    "metadata": [
      {
        "name": "keywords",
        "content": "Information Architecture, AI, Content Strategy, Portfolio"
      },
      {
        "name": "author",
        "content": "Bipin Pandey"
      }
    ],
    "navbar": {
      "title": "Bipin Pandey",
      "logo": {
        "alt": "Bipin Pandey Logo",
        "src": "img/logo.png"
      },
      "items": [
        {
          "to": "/about",
          "label": "About",
          "position": "left"
        },
        {
          "to": "/portfolio/intro",
          "label": "Portfolio",
          "position": "left"
        },
        {
          "to": "/blog",
          "label": "Blog",
          "position": "left"
        },
        {
          "href": "https://github.com/Bipin-24",
          "label": "GitHub",
          "position": "right"
        },
        {
          "href": "https://www.linkedin.com/in/bipin-pandey-3594961a/",
          "label": "LinkedIn",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Explore",
          "items": [
            {
              "label": "About",
              "to": "/about"
            },
            {
              "label": "Portfolio",
              "to": "/portfolio/intro"
            },
            {
              "label": "Blog",
              "to": "/blog"
            }
          ]
        },
        {
          "title": "Connect",
          "items": [
            {
              "label": "LinkedIn",
              "href": "https://www.linkedin.com/in/bipin-pandey-3594961a/"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/Bipin-24"
            },
            {
              "label": "Twitter (X)",
              "href": "https://twitter.com/"
            }
          ]
        }
      ],
      "copyright": "© 2025 Bipin Pandey. Crafted with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "future": {
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
